# Generated by Django 4.2.7 on 2023-11-19 13:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=256, verbose_name='firstname')),
                ('surname', models.CharField(max_length=256, verbose_name='surname')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=256, verbose_name='firstname')),
                ('surname', models.CharField(max_length=256, verbose_name='surname')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CardStudent',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.student')),
                ('id_student', models.CharField(max_length=256, verbose_name='id_student')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number', models.IntegerField(verbose_name='Number')),
                ('deleted', models.BooleanField(default=False)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='TermCourses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_begin', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.courses')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.terms')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='student',
            field=models.ManyToManyField(to='mainapp.student'),
        ),
    ]
